### PR TITLE
Disable Length checks

### PR DESCRIPTION
**Pull request by GordonDiggs**
We never follow them, and always have to merge around them

@codeclimate/review

### CODE REVIEW

**Comment by wfleming** [comment]
I think _always_ is an overly strong statement: I can think of many times we've taken the time to refactor due to long method issues: normally when we ignore them it's because the method is a giant hash of attrs to get passed elsewhere.

Personally, I also think the long class issues are helpful as a warning of "hey, this class might be getting out of hand.".

**Comment by pbrisbin** [comment]
I (basically) agree with @wfleming. Yes there are false-positives that we often merge around (mostly because of the Hash-happiness of Mongo), but I like seeing the issues come up and choosing when/if to do that. I also like seeing when a class gets "Long" and deciding to deal with it now or defer (but not ignore the issue).

**Comment by maxjacobson** [comment]
We should make gates 😄

**Comment by GordonDiggs** [comment]
This went about as I expected! Closing.

**Pull request closed without merging**
