### PR TITLE
Add eslintrc

### PR DESCRIPTION
**Pull request by jpignata**
Taken from the default configuration we generate via codeclimate with
the small change of allowing trailing commas (comma-dangle).

@codeclimate/review

### CODE REVIEW

**Comment by GordonDiggs** [comment]
We already [have an eslintrc config](https://github.com/codeclimate/styleguide/blob/master/.eslintrc.js)

**Comment by jpignata** [comment]
Ahh, I missed this by just glancing at the `ls` of the directory. Amended to unhide that.

**Comment by jpignata** [comment]
@GordonDiggs I'd like to allow us to use trailing commas on node projects for the same reason we do it within Ruby. I see there's a compatibility issues with versions of IE less than 8 with this behavior, but I'm not certain we actually support > IE 8? Opinions?

**Comment by GordonDiggs** [comment]
@jpignata I'm +1 on that

**Comment by jpignata** [comment]
@GordonDiggs Done.

**Comment by GordonDiggs** [comment]
LGTM

**Pull request merged**
