### PR TITLE
Always use quotes for attributes in js markup

### PR DESCRIPTION
**Pull request by ABaldwinHunter**
Since quotes are required sometimes, as when adding multiple classes separated by spaces, quoting
consistently should reduce thought involved.

Additional benefit is a smaller diff when new attributes are added.

@codeclimate/review Curious about your thoughts.

### CODE REVIEW

**Comment by GordonDiggs** [comment]
I support this, but I think we probably need a new `markup/README.md` since this could apply to more than just handlebars/js

**Comment by GordonDiggs** [comment]
I also think the example could be more generic to better match others in this repo

**Comment by pbrisbin** [comment]
FWIW: i liked the original suggest of "markup" more than "template". This rule could just as well apply to `foo.html` as it does `foo.hbs` or `foo.html.slim`.

**Comment by wfleming** [comment]
If we're going to bikeshed the directory/language name, "HTML" seems simplest & most accurate to me.

**Comment by ABaldwinHunter** [comment]
@codeclimate/review Thanks for the feedback!

I think that's a good point about using `HTML` as the language and fine by me. Updated pull & ready for another look.

**Comment by GordonDiggs** [comment]
I like the language now - would still like to see the example class names be more generic though

**Comment by ABaldwinHunter** [comment]
Updated to use more generic example classes 👍

**Comment by GordonDiggs** [comment]
LGTM

**Pull request merged**
