### PR TITLE
Separate guides by language

### PR DESCRIPTION
**Pull request by wfleming**
I felt the single README was getting kind of unweildy with 3 distinct
languages with different sections. This breaks up individual languages
into their own directories.

Thoughts, @codeclimate/review

### CODE REVIEW

**Comment by GordonDiggs** [comment]
I like this - one suggestion. If you name them `ruby/README.md`, I believe Github will display them automatically when you click on `ruby` in the tree view

**Comment by ABaldwinHunter** [comment]
Fine by me. Curious about other opinions.

_#Styling the style guide_

**Comment by wfleming** [comment]
Good suggestion @GordonDiggs. Done.

**Comment by GordonDiggs** [comment]
:+1:

**Pull request merged**
